# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('brief', models.CharField(default='你想看见什么呢?', max_length=150, verbose_name='文章简介')),
                ('article', models.TextField(verbose_name='正文')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('picture', models.ImageField(upload_to='', verbose_name='配图')),
            ],
        ),
    ]
