# Generated by Django 2.0.3 on 2018-07-19 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('brief', models.CharField(max_length=150, verbose_name='文章简介')),
                ('article', models.TextField(verbose_name='正文')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('picture', models.CharField(default='../static/picture/i.jpg', max_length=150, verbose_name='配图地址')),
                ('kind', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mean', models.TextField(verbose_name='正文')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
