# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='brief',
            field=models.CharField(max_length=150, verbose_name='文章简介'),
        ),
    ]
