# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171021_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-time']},
        ),
    ]
